server.port=8081

spring.sql.init.schema-locations=classpath:/data/schema.sql
spring.sql.init.data-locations=classpath:/data/data.sql
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.generate-unique-name=false
spring.datasource.name=projweb

logging.level.org.springframework.security=DEBUG
